#!/bin/bash

retry=""
overwrite=""

if [[ $1 == "-r" ]]; then
  shift
  retry="-i -r"
  overwrite="set xfer:clobber 1"
fi

shipment=$1
url=$2
namespace=$3

cd /htprep/toingest/$namespace
lftp -c "open $url; $overwrite; mget *"
BUNDLE_GEMFILE=~libadm/ruby/Gemfile bundle exec ruby ~libadm/ruby/get_http_filenames.rb $url $namespace
mv ${namespace}_$shipment.txt ~libadm/ingest
enqueue $retry -p simple -n $namespace ~libadm/ingest/${namespace}_$shipment.txt
