#!/bin/bash

retry=""
overwrite=""

if [[ $1 == "-r" ]]; then
  shift
  retry="-r"
  overwrite="set xfer:clobber 1"
fi

shipment=$1
url=$2
namespace=$3

cd /htprep/toingest/$namespace
lftp -c "open '$url'; $overwrite; mget *"
lftp -c "open '$url'; ls" | sed 's/.* //' | grep '.zip' | sed 's/\.zip//' | tr '+=' ':/' > ~libadm/ingest/${namespace}_$shipment.txt
enqueue -i $retry -p simple -n $namespace ~libadm/ingest/${namespace}_$shipment.txt
