#!/bin/bash

retry=""
overwrite=""

if [[ $1 == "-r" ]]; then
  shift
  retry="-r"
  overwrite="set xfer:clobber 1"
fi


if [[ -z "$3" || -z "$2" || -z "$1" ]];
then echo "Usage: $0 namespace box_folder idfile"; exit 1;
fi

namespace=$1
boxfolder=$2
barcodes=$3

lftp -f <(echo "open ftp.box.com"; echo $overwrite; echo "lcd /htprep/toingest/$namespace"; echo "cd hathitrust-cloud-validator/'$boxfolder'"; cat $barcodes | sed 's/\(.*\)/mget \1.zip*/' | tr ':/' '+='; echo "exit")

while read id; do
  escaped=`echo "$id" | tr ':/' '+='`
  zipname="/htprep/toingest/$namespace/${escaped}.zip"

  if ! [ -e "$zipname" ]; then
    if [ -e "${zipname}.001" ]; then
      cat "$zipname".* > "$zipname" && rm "$zipname".*
    fi
  fi
done < "$barcodes"

enqueue -i $retry -p simple -n $namespace $barcodes
