#!/bin/bash

retry=""

if [[ $1 == "-r" || $1 == "-R" ]]; then
  retry=$1
  shift
fi

shipment=$1
url=sftp://tang.umdl.umich.edu:/quod-prep/prep/d/dcu/DCU_Image_Processing/7_Direct_Ingest/$shipment/

~libadm/bin/get_lftp $retry $shipment $url mdp
