#!/bin/bash

retry=""

if [[ $1 == "-r" || $1 == "-R" ]]; then
  retry=$1
  shift
fi


shipment=$1
url="https://$BERKELEY_USERINFO@digitalassets.lib.berkeley.edu/hathitrust_submission/$shipment/"

~libadm/bin/get_lftp $retry $shipment "$url" ucbk
