#!/bin/bash

retry=""

if [[ $1 == "-r" ]]; then
  shift
  retry="-r"
fi


shipment=$1
#url=http://hathi.library.illinois.edu/feed/packages/BrittleBooks/2018/submissions/$shipment
url=http://hathi.library.illinois.edu/feed/packages/BrittleBooks/ready/$shipment

~libadm/bin/get_http $retry $shipment $url uiuc
