#!/bin/bash

retry=""

if [[ $1 == "-r" ]]; then
  shift
  retry="-r"
fi


shipment=$1
url="https://$BERKELEY_USERINFO@digitalassets.lib.berkeley.edu/hathitrust_submission/$shipment/"

echo ~libadm/bin/get_lftp $retry $shipment "$url" ucbk
