#!/bin/bash

retry=""

if [[ $1 == "-r" || $1 == "-R" ]]; then
  retry=$1
  shift
fi


shipment=$1
#url=http://hathi.library.illinois.edu/feed/packages/BrittleBooks/2018/submissions/$shipment
url=http://hathi.library.illinois.edu/feed/packages/BrittleBooks/ready/$shipment

~libadm/bin/get_lftp $retry $shipment $url uiuc
